### ISSUE TITLE
试过nestjs7能跑起来吗？

### ISSUE THREAD

**Issue by xxstop** [2234839/nest.js_aliyun_serverless#2]
我试了之后出来这样的提示：
```
{
  "errorMessage": "express_1.default is not a function",
  "errorType": "TypeError",
  "stackTrace": [
    "TypeError: express_1.default is not a function",
    "at (/code/dist/index.js:8:30)",
    "at Module._compile (internal/modules/cjs/loader.js:701:30)",
    "at Module._extensions..js (internal/modules/cjs/loader.js:712:10)",
    "at Module.load (internal/modules/cjs/loader.js:600:32)",
    "at tryModuleLoad (internal/modules/cjs/loader.js:539:12)",
    "at Module._load (internal/modules/cjs/loader.js:531:3)",
    "at Module.require (internal/modules/cjs/loader.js:637:17)",
    "at require (internal/modules/cjs/helpers.js:22:18)"
  ]
}
```

**Comment by 2234839** [comment]
> 
> 
> 我试了之后出来这样的提示：
> 
> ```
> {
>   "errorMessage": "express_1.default is not a function",
>   "errorType": "TypeError",
>   "stackTrace": [
>     "TypeError: express_1.default is not a function",
>     "at (/code/dist/index.js:8:30)",
>     "at Module._compile (internal/modules/cjs/loader.js:701:30)",
>     "at Module._extensions..js (internal/modules/cjs/loader.js:712:10)",
>     "at Module.load (internal/modules/cjs/loader.js:600:32)",
>     "at tryModuleLoad (internal/modules/cjs/loader.js:539:12)",
>     "at Module._load (internal/modules/cjs/loader.js:531:3)",
>     "at Module.require (internal/modules/cjs/loader.js:637:17)",
>     "at require (internal/modules/cjs/helpers.js:22:18)"
>   ]
> }
> ```

我待会试试

**Comment by 2234839** [comment]
@xxstop 你看下我更新的内容，这个问题是你直接用新版 tsconfig 覆盖了旧版的问题。` esModuleInterop": true ` 选项是需要保留的

**Comment by wishcn** [comment]
@2234839 
fun打包用的什么版本，我发现3.6.15这个最新版本unzip不行，最后切换到3.6.2这个版本可以了。但是缺少PATCH请求。Nodejs也只能用10。

**Comment by wishcn** [comment]
@2234839 按你的提示，我试了下，确实成功了。谢谢~

**Comment by 2234839** [comment]
> 
> 
> @2234839
> fun打包用的什么版本，我发现3.6.15这个最新版本unzip不行，最后切换到3.6.2这个版本可以了。但是缺少PATCH请求。Nodejs也只能用10。

我看了下我电脑上安装的是 3.6.14 版本的

**Comment by wishcn** [comment]
> > @2234839
> > fun打包用的什么版本，我发现3.6.15这个最新版本unzip不行，最后切换到3.6.2这个版本可以了。但是缺少PATCH请求。Nodejs也只能用10。
> 
> 我看了下我电脑上安装的是 3.6.14 版本的

难道跟windows有关系？我去试试3.6.14呢。
![122](https://user-images.githubusercontent.com/4318498/91824807-ef622b00-ec6d-11ea-8277-fb8d93a238fa.png)

**Comment by 2234839** [comment]
> 
> 
> > > @2234839
> > > fun打包用的什么版本，我发现3.6.15这个最新版本unzip不行，最后切换到3.6.2这个版本可以了。但是缺少PATCH请求。Nodejs也只能用10。
> > 
> > 
> > 我看了下我电脑上安装的是 3.6.14 版本的
> 
> 难道跟windows有关系？我去试试3.6.14呢。
> ![122](https://user-images.githubusercontent.com/4318498/91824807-ef622b00-ec6d-11ea-8277-fb8d93a238fa.png)

这个我就不太清楚了，我对 fun 不是很了解。这是我使用的部署命令 `& "~/.aliyun-serverless/bin/fun.exe" deploy -t d:\code\nest\nest-test\template.yml -y`,这个命令来自
![图片](https://user-images.githubusercontent.com/28727933/91825282-a1015c00-ec6e-11ea-9c4c-c83cf2b87607.png)阿里云提供的这个vscode插件自动执行的

**Comment by wishcn** [comment]
我走的是webstorm.😂
流程是：
```
npm install
npm build

fun deploy
fun nas sync
```

不知道这个流程对不？

如果需要fun工具做build，本地应该需要安装docker好像才行？

**Comment by 2234839** [comment]
@xxstop  我也是本地编译的 `& "~/.aliyun-serverless/bin/fun.exe" deploy -t d:\code\nest\nest-test\template.yml -y` 这个是我用来部署的命令

**Comment by wishcn** [comment]
试了很久，3.6.14测试过了。不安装typeorm啥事情都没有，一切正常。

**Comment by wishcn** [comment]
typeorm -> yargonaut -> figlet 这个依赖里面有Patorjk's Cheese.flf，非法字符导致。

**Comment by 2234839** [comment]
> yargonaut

( ´･･)ﾉ(._.`) 这 ...

**Comment by wishcn** [comment]
😂我也觉得好难...开始还以为只是版本的问题。而且这个依赖还是prod时的依赖，并不能通过prod模式排除掉。
